# Defaults
replicaCount: 3

image:
  repository: akhomchanka/ruby-server
  pullPolicy: IfNotPresent
  tag: 0

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"