name: build-deploy-test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t akhomchanka/ruby-server:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: docker push akhomchanka/ruby-server:${{ github.sha }}

  deploy-and-test:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Set up Kubernetes-in-Docker (KIND)
        uses: helm/kind-action@v1.8.0 

      - name: Deploy with Helm
        run: |
          helm upgrade --install my-ruby-app ./helm/ruby-server --set image.repository=akhomchanka/ruby-server --set image.tag=${{ github.sha }}

      - name: Test endpoint
        run: |
          # Port-forwarding
          kubectl port-forward service/my-ruby-app 8080:80 &
          sleep 10 # Wait for port-forwarding to establish

          # Test 1: /healthcheck
          echo -e "GET /healthcheck HTTP/1.1\r\n" | nc localhost 8080
          sleep 5

          # Test 2: /nonexistent (any other endpoint)
          echo -e "GET /nonexistent HTTP/1.1\r\n" | nc localhost 8080
